athena:
  security:
    auth:
      enabled: true
      ignore-urls:
        - /auth/login
        - /profile/ping
        - /template/test
    token:
      type: local
      jwt:
        enabled: false
    authorization:
      enabled: false
    user:
      jpa:
        enabled: true
